name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Publish
      run: |
        poetry install --no-dev
        sq --help
        poetry publish --build -u __token__ -p ${{ secrets.PYPI_PASS }}
